### ISSUE TITLE
Symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by mschonvogel** [ethand91/mediasoup-ios-client#1]
Hey, thank you for starting this project! However, after importing the frameworks, I cant build (it seems like the lib was only build for iOS-arm64):

```
ld: warning: ignoring file /Users/asd/Projects/test/test-mediasoup/mediasoup_client_ios.framework/mediasoup_client_ios, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Device", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
```

Am I missing something?
Thanks!

**Comment by ethand91** [comment]
Hello, thanks for the report!
While the lib supports x86_64, the produced framework may not have included it.
I will take a look into it, in the meantime does it build if you set the build architectures to either 64 bit only or arm64?

Also if you are planning to test this on a simulator, unlike android you cannot use the device's camera/mic.

**Comment by mschonvogel** [comment]
Thank you for your quick response.

No, setting the architecture to arm64 and trying to run it on my iPhone 11 Pro didn't work.
![image](https://user-images.githubusercontent.com/370839/75023125-92541400-5497-11ea-853c-0867d9b97e82.png)

My plan is to use the device for testing but the app should still run in the simulator.
I'd really appreciate if you could build and upload a version of the lib that includes all required architectures.

**Comment by mschonvogel** [comment]
I've now followed your Instructions from [here](https://github.com/ethand91/mediasoup-ios-client/blob/master/build/mediasoup%403%20iOS%20WebRTC%20Framework%20Build%20Instructions.md) and built the libwebrtc.a, libmediasoup.a, libsdptransform.a files and replaced the binaries in `mediasoup_client_ios.framework` and `WebRTC.framework`. Not sure what to do with `libsdptransform.a`, though. It's still not compiling. Any advice is much appreciated.

Btw. there is a WebRTC pod. Why are you not using it?

**Update:** 
I managed to compile the app, with your binaries now. I think I forgot to not only **Embed Frameworks** but also add them to the **Link Binary with Libraries** build phase.
![image](https://user-images.githubusercontent.com/370839/75046063-b712b080-54c4-11ea-9877-3dbbe85b4914.png)

Also, I had to **disable Bitcode**.

Replacing the binaries with the ones that I built didn't work. The app compiled but then instantly crashed:

```
dyld: Library not loaded: @rpath/mediasoup_client_ios.framework/mediasoup_client_ios
  Referenced from: /private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Fuu
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios: code signature invalid for '/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios'

	/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios: code signature invalid for '/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios'

	/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios: stat() failed with errno=1
	/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios: code signature invalid for '/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios'

	/private/var/containers/Bundle/Application/6002C25B-4F05-451A-AA20-7A3F626754B4/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios: stat() failed with errno=1
```

Setting the `Disable Library Validation Entitlement` to `YES` didn't help.

Did you manage to compile and run the sample app in the simulator?

**Comment by ethand91** [comment]
> I'd really appreciate if you could build and upload a version of the lib that includes all required architectures.

Will do, however I'm not sure how long it will take.

>Not sure what to do with libsdptransform.a, though. It's still not compiling. Any advice is much appreciated

lipsdptransform also needs to be included in order to parse SDP. What errors do you get when compiling?

>Btw. there is a WebRTC pod. Why are you not using it?

mediasoup requires version m73/m74 of the webrtc lib, as far as I'm aware the WebRTC pod has not been updated in a while.
https://mediasoup.org/documentation/v3/libmediasoupclient/installation/

>Also, I had to disable Bitcode.

Yes, currently you need to disable Bitcode atm, however I hope to also support this in the future.

>Replacing the binaries with the ones that I built didn't work. The app compiled but then instantly crashed:

Seems to be a code signing error.

>Did you manage to compile and run the sample app in the simulator?

No while the library supports arm64/x86_64, the built framework does not, I will make a couple of enhancement issues to track this and bitcode support.

**Comment by ethand91** [comment]
I do admit though, atm building/implementing this library is a struggle.
I'm hoping uploading it to cocoapods will reduce some of the implementation issues.  ><

**Comment by ethand91** [comment]
@mschonvogel 
x86_64 arch has been supported! 

Could you please add the below pod and see if it works for you?

`pod "mediasoup_ios_client", :git => "https://github.com/ethand91/mediasoup-ios-client.git", :submodules => true, :tag => "1.0.0"`

I tried this with an actual device and simulator and both worked.
You cannot use the simulator's camera device, however it can play a remote stream.

The sample I used:
https://github.com/ethand91/mediasoup-ios-client-sample

**Comment by mschonvogel** [comment]
Thank you @ethand91 I tested it and it works!
