### ISSUE TITLE
 pod installing mediasoup_ios_client error

### ISSUE THREAD

**Issue by cainxx** [ethand91/mediasoup-ios-client#10]
[!] Error installing mediasoup_ios_client
[!] Failed to download 'mediasoup_ios_client': [!] /usr/bin/git -C /var/folders/s0/h_pcj4wj3hxfy4y0k2v8ryz40000gp/T/d20200303-91582-1ivqlky submodule update --init --recursive

Submodule path 'mediasoup-client-ios/dependencies/libmediasoupclient': checked out 'a75cf2a77ef1dd6b0b52b1a16596d65ef8fe6e83'
Submodule 'mediasoup-client-ios/dependencies/libmediasoupclient' (https://github.com/ethand91/libmediasoupclient.git) registered for path 'mediasoup-client-ios/dependencies/libmediasoupclient'
Submodule 'mediasoup-client-ios/dependencies/webrtc/src' (https://github.com/ethand91/webrtc-mac-src.git) registered for path 'mediasoup-client-ios/dependencies/webrtc/src'
Cloning into '/private/var/folders/s0/h_pcj4wj3hxfy4y0k2v8ryz40000gp/T/d20200303-91582-1ivqlky/mediasoup-client-ios/dependencies/libmediasoupclient'...
Cloning into '/private/var/folders/s0/h_pcj4wj3hxfy4y0k2v8ryz40000gp/T/d20200303-91582-1ivqlky/mediasoup-client-ios/dependencies/webrtc/src'...
error: Server does not allow request for unadvertised object fba755df2ea8163a5bbefb7e8e7c58dec433534a
Fetched in submodule path 'mediasoup-client-ios/dependencies/webrtc/src', but it did not contain fba755df2ea8163a5bbefb7e8e7c58dec433534a. Direct fetching of that commit failed.

**Comment by ethand91** [comment]
Hello, could you try running the below commands:
```bash
pod repo update
pod deintegrate
pod install
```
