### ISSUE TITLE
Update libmediasoup dependency

### ISSUE THREAD

**Issue by cefiro666** [ethand91/mediasoup-ios-client#103]
Greetings!

I would like to express my deep gratitude to you for the developed library.
At the moment I'm working on a data dependency for your library, specifically libmediasoup. I may build the library that is stored in your fork which is the main repository, but I would like to build it with the main libmediasoup (3.1.5) version of the library.

Could you help me with this?)

**Comment by cefiro666** [comment]
I figured it out myself, thanks)

**Comment by Chaehui-Seo** [comment]
Hello, could you please share the solution? I'm facing the same problem, too.
