### ISSUE TITLE
PeerConnectionFactory

### ISSUE THREAD

**Issue by yuvalt** [ethand91/mediasoup-ios-client#11]
One of the issues I've ben stumbling on, is the fact that libmediasoupclient always uses the C++ APIs, while in fact in some cases, specifically MacOS (but probably also others), the video/audio encoders/decoders are defined in the Objective C layer. Since libmediasoupclient uses the default factories not all the features of the platform are explored or used. The fact that the iOS/Mac client does not pass its own factories causes that H264 uses ffmpeg instead of hardware decoding/encoding. I've implemented some fix in my branch as a gap measure to fix it, but I'm not submitting as PR since there might be cleaner way of handling that.

**Comment by ethand91** [comment]
Understood.
Your fix seems to be better than the implementation right now so feel free to issue a pull request if you want.
Implementing a cleaner solution could be done later.

**Comment by ethand91** [comment]
This was mainly created to run on iOS, will close for now but if you manage to find a solution to this issue please share how you did it.

**Comment by dh95277** [comment]
> One of the issues I've ben stumbling on, is the fact that libmediasoupclient always uses the C++ APIs, while in fact in some cases, specifically MacOS (but probably also others), the video/audio encoders/decoders are defined in the Objective C layer. Since libmediasoupclient uses the default factories not all the features of the platform are explored or used. The fact that the iOS/Mac client does not pass its own factories causes that H264 uses ffmpeg instead of hardware decoding/encoding. I've implemented some fix in my branch as a gap measure to fix it, but I'm not submitting as PR since there might be cleaner way of handling that.

can you shared
