### ISSUE TITLE
SendTransportListenerWrapper::onProcude should use promise

### ISSUE THREAD

**Issue by yuvalt** [ethand91/mediasoup-ios-client#12]
The libmediasoupclient library uses promises in these case, since you may need to perform an async operation before returning a value. I've fixed this in my branch but was unable to create a PR since I made a few other small unrelated fixes. You can see the commit here: https://github.com/yuvalt/mediasoup-ios-client/commit/37d8ad9bbe156398923a5eebe6b3bcc9e441caab

**Comment by ethand91** [comment]
This was on the to-do list, you are correct in saying you may need to perform an async operation such as sending a request to the server without making that operation sync.
If it's not possible to create a PR I will implement it on my end if that's okay with you?

**Comment by ethand91** [comment]
Implemented
