### ISSUE TITLE
not enable sctpCapabilities

### ISSUE THREAD

**Issue by jiaoshenmene** [ethand91/mediasoup-ios-client#15]
please support sctpCapabilities ,thanks

**Comment by ethand91** [comment]
Will look into it

**Comment by ethand91** [comment]
This requires updating the inner libmediasoup client, which is on the TODO.
Try and implement this alongside it.

**Comment by ethand91** [comment]
Try updating the pod to version 1.3.0, I updated the libs.

**Comment by jiaoshenmene** [comment]
thank you very much
