### ISSUE TITLE
Asking questions

### ISSUE THREAD

**Issue by txyhost** [ethand91/mediasoup-ios-client#16]
First study mediasoup webrtc

How to modify request.swift for protoo.websocket used by server

What information can I refer to

**Comment by ethand91** [comment]
>What information can I refer to

You could look at the server app and try to implement a way to communicate with it.

I will try to implement a protoo client for ios, when I get time if you can wait.

**Comment by ksojitra747** [comment]
Hello is there any update to connect protoo client with MediaSoup demo by you. I see your comments that you are going to add but I guess still we have no update. Please update for the same. We are eagerly waiting.

**Comment by ethand91** [comment]
My macbook broke so I can't anymore until I get a new Macbook :(
