### ISSUE TITLE
Support cocoapods

### ISSUE THREAD

**Issue by ethand91** [ethand91/mediasoup-ios-client#2]
Support cocoapods so the framework does not need to be uploaded each time.

Due to the dependencies and build steps needed this is pretty hard to implement.
If anyone has any experience uploading objective-C++ frameworks to cocoapods, help would be greatly appreciated.

**Comment by mschonvogel** [comment]
Maybe the easiest way to do it, is to build universal binaries for both your mediasoup wrapper and webrtc, upload it as a [github release](https://help.github.com/en/github/managing-large-files/distributing-large-binaries) and then download it via cocoapods?

**Comment by ethand91** [comment]
@mschonvogel Thanks for the advice, I'll try to get it implemented as a github release for now.

**Comment by mschonvogel** [comment]
Thanks, sounds good! Do you know already when you've got time to upload the binaries and the pod?

**Comment by ethand91** [comment]
I'll try and get it done this week.

**Comment by ethand91** [comment]
Added cocoapod support (Git only)

**Comment by mschonvogel** [comment]
Thank you so much @ethand91
