### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by aparandiy** [ethand91/mediasoup-ios-client#20]
Hi, sorry for my stupid question, but I need some explanations during the implementation this line of code: 

// Communicate with our server app to retrieve router RTP capabilities
NSString *routerRtpCapabilities = [mySignalling request:@"getRouterRtpCapabilities"];

So, can you explain me what is the object "mySignalling" and where can i get it? or create some working demo iOS project - so i can better understand how it works 

Thanks

**Comment by ethand91** [comment]
mySignalling is the mediasoup server application.
Below is the server I use to test this is:
https://github.com/ethand91/mediasoup-sample-server
