### ISSUE TITLE
CFBundleIdentifier Collision

### ISSUE THREAD

**Issue by mschonvogel** [ethand91/mediasoup-ios-client#21]
When trying to submit the app, I'm getting a transporter error with version 1.2.3: 

```
[01:06:11]: ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.webrtc.WebRTC' under the iOS application 'fuu.app'."
ERROR ITMS-90205: "Invalid Bundle. The bundle at 'fuu.app/Frameworks/mediasoup_client_ios.framework' contains disallowed nested bundles."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'fuu.app/Frameworks/mediasoup_client_ios.framework' contains disallowed file 'Frameworks'."
\nERROR ITMS-90206: "Invalid Bundle. The bundle at 'fuu.app/Frameworks/mediasoup_client_ios.framework' contains disallowed file 'Frameworks'."ifier value 'org.webrtc.WebRTC' under the iOS application 'fuu.app'."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by ethand91** [comment]
Will look into it.
However I don't have a paid developer account, so any help is appreciated.

**Comment by mschonvogel** [comment]
Thank you. It seems like it's because of your changes of `CodeResources` in https://github.com/ethand91/mediasoup-ios-client/commit/b506d687f73f09fef95b82d1787c630e48fa8cad 

But I don't really know why you added that configuration…

**Comment by ethand91** [comment]
Thanks for the help, seems I left the Framework in when running tests...
I've removed it and released 1.2.4.
Could you try and see if that works?

**Comment by mschonvogel** [comment]
Yes, it works! Thanks

**Comment by ethand91** [comment]
Glad to hear.
