### ISSUE TITLE
How to support H264

### ISSUE THREAD

**Issue by txyhost** [ethand91/mediasoup-ios-client#24]
How to support H264

**Comment by ethand91** [comment]
The webrtc library will need to be built enabling H264, I will try and implement this while upgrading the libmediasoupclient

**Comment by ethand91** [comment]
You would need to build the webrtc libraries yourself and enable the h264 flag.

If more people want this I will try to implement it, however with H264 enabled it may not be compatible with some Android devices so closing for now.

**Comment by thayallans** [comment]
Hey! Was this is ever implemented ?
