### ISSUE TITLE
Crash when using method getRtpParameters from Producer

### ISSUE THREAD

**Issue by OrchidVC** [ethand91/mediasoup-ios-client#27]
Error:
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is object

When call function getRtpParameters from Producer

**Comment by ethand91** [comment]
Thanks will see if can reproduce

**Comment by ethand91** [comment]
fixed in 1.3.1
