### ISSUE TITLE
#import "Device.hpp" file not found

### ISSUE THREAD

**Issue by WHLwhlww** [ethand91/mediasoup-ios-client#28]
#import "Device.hpp" file not found
#import "Logger.hpp" file not found
#import "Mediasoupclient.h" file not found
...
help me .thank you !

**Comment by ethand91** [comment]
Hello, Are you programming in Obj-C or Swift?
You should be able to use the library by just importing the below:

```
#import "mediasoup_client_ios/Mediasoupclient.h
```

Failing that check your header search paths etc.

**Comment by WHLwhlww** [comment]
What I use is obj-c, the demo I directly clone down will directly report the error, the header file can not find, how to solve, help me, thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ethan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 下午4:05
收件人:&nbsp;"ethand91/mediasoup-ios-client"<mediasoup-ios-client@noreply.github.com&gt;;
抄送:&nbsp;"王海林"<820746480@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ethand91/mediasoup-ios-client] #import "Device.hpp" file not found (#28)





 
Hello, Are you programming in Obj-C or Swift?
 You should be able to use the library by just importing the below:
 #import "mediasoup_client_ios/Mediasoupclient.h  
Failing that check your header search paths etc.

**Comment by ethand91** [comment]
Have you set the header search paths correctly?

**Comment by WHLwhlww** [comment]
I directly global search, but did not find, your project is not a few files, download down a lot of files can not find, can send a more complete project? thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ethan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 上午10:00
收件人:&nbsp;"ethand91/mediasoup-ios-client"<mediasoup-ios-client@noreply.github.com&gt;;
抄送:&nbsp;"王海林"<820746480@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ethand91/mediasoup-ios-client] #import "Device.hpp" file not found (#28)





 
Have you set the header search paths correctly?
