### ISSUE TITLE
 'error creating transceiver'

### ISSUE THREAD

**Issue by DinuNuta** [ethand91/mediasoup-ios-client#29]
in v 1.3.3
when i'm try to call transport.produce crash with  'error creating transceiver'
please help me, thanks 

[TransportWrapper nativeProduce:listener:track:encodings:codecOptions:appData:]

**Comment by ethand91** [comment]
Could you share the error logs?
Also does it work using version 1.2.X version of the library?

**Comment by ethand91** [comment]
This may have been fixed in version 1.3.5, could you try it?

**Comment by ethand91** [comment]
are you using encodings in the produce request?
It seems that m79 branch breaks this, I will look into this once the libs have been updated to m84.
For now could you pass nill for encodings?

**Comment by DinuNuta** [comment]
I tried to pass nil encodings, it's work but not call delegate onProduce.
Tested version 1.2.X and 1.3.5, on IOS 12, 13 
Thanks a lot!
