### ISSUE TITLE
Error "Failed to set remote offer sdp: Duplicate a=mid value '2'"

### ISSUE THREAD

**Issue by DinuNuta** [ethand91/mediasoup-ios-client#35]
It happen whem i'm trying to receive 2 and more consumers! 
"
Receive: message
SocketNotificationResponse(method: EBSWebRTCiOS.Methods.newConsumer, payload: Optional({
  "kind" : "audio",
  "appData" : {
    "peerId" : "5e900aad9373cc2d9546806d",
    "source" : "mic"
  },
  "type" : "simple",
  "peerId" : "5e900aad9373cc2d9546806d",
  "id" : "a8c5c217-f7d4-4896-8732-97617679c52b",
  "producerPaused" : false,
  "producerId" : "2daec80e-721e-4113-97e6-79084fce3a11",
  "rtpParameters" : {
    "codecs" : [
      {
        "channels" : 2,
        "payloadType" : 100,
        "rtcpFeedback" : [

        ],
        "mimeType" : "audio\/opus",
        "parameters" : {
          "sprop-stereo" : 1,
          "usedtx" : 1,
          "useinbandfec" : 1,
          "minptime" : 10
        },
        "clockRate" : 48000
      }
    ],
    "headerExtensions" : [
      {
        "parameters" : {

        },
        "encrypt" : false,
        "uri" : "urn:ietf:params:rtp-hdrext:sdes:mid",
        "id" : 1
      },
      {
        "id" : 4,
        "parameters" : {

        },
        "encrypt" : false,
        "uri" : "http:\/\/www.webrtc.org\/experiments\/rtp-hdrext\/abs-send-time"
      },
      {
        "parameters" : {

        },
        "encrypt" : false,
        "uri" : "urn:ietf:params:rtp-hdrext:ssrc-audio-level",
        "id" : 10
      }
    ],
    "encodings" : [
      {
        "ssrc" : 608869349
      }
    ],
    "rtcp" : {
      "reducedSize" : true,
      "mux" : true,
      "cname" : "iaBbtBsUsI5\/yaN\/"
    },
    "mid" : "2"
  }
}))
consumeTrack(consumerInfo:)
Optional("{\n  \"peerId\" : \"5e900aad9373cc2d9546806d\",\n  \"source\" : \"mic\"\n}")
2020-06-01 13:22:11.186960+0300 EBSWebRTCiOS_Example[371:42689] *** Terminating app due to uncaught exception 'RuntimeException', reason: 'Failed to set remote offer sdp: Duplicate a=mid value '2'.'"

**Comment by ethand91** [comment]
This seems to be an issue with the current version of libmediasoupclient being used.
https://github.com/versatica/libmediasoupclient/issues/83

Should be fixed when the inner libmediasoupclient is updated.

**Comment by DinuNuta** [comment]
Ther sad is probleme in this mediasoup-iOS client

**Comment by DinuNuta** [comment]
Thanks for your support! 
You are very active and responsive.

**Comment by ethand91** [comment]
Hello, libmediasoupclient/libwebrtc has been updated to m84 can you try it?
version 1.4.1

**Comment by DinuNuta** [comment]
Thanks for your support!
Now works fine. 
Tested with multiple connections, works ok.

**Comment by ethand91** [comment]
Great! Thanks for confirming
