### ISSUE TITLE
Can`t build mediasoup-ios-client source code

### ISSUE THREAD

**Issue by LucasDang** [ethand91/mediasoup-ios-client#38]
Thanks for your share!

According to your instructions, I had compiles libwebRTC.a and libmediasoupclient.a.
But when compile source code in Xcode, I got error.
In webrtc module, it's warning "Must define either WEBRTC_WIN or WEBRTC_POSIX."!
I`m not good in c++, Can you tell me how to resolve such as problems as this?

**Comment by ethand91** [comment]
The webrtc src files need to be "patched" in order to build successfully.
(Sorry I didn't include this in the build instructions)

Fastest way is to replace the webrtc src directory with the following repo:
https://github.com/ethand91/webrtc-mac-src/tree/m84

**Comment by LucasDang** [comment]
Thanks so much!
