### ISSUE TITLE
Can't publish app on TestFlight

### ISSUE THREAD

**Issue by DinuNuta** [ethand91/mediasoup-ios-client#39]
I try to publish Example app with mediasoup-ios-client integrated like a pod 
had errors :
![Screen Shot 2020-06-09 at 10 10 09](https://user-images.githubusercontent.com/22508915/84119308-d9611780-aa3c-11ea-95f4-93d83991afb1.png)
![Screen Shot 2020-06-09 at 10 38 39](https://user-images.githubusercontent.com/22508915/84120363-68bafa80-aa3e-11ea-9fac-58659bf5eeb2.png)
Could you help me to solve this problem. Thanks!

**Comment by ethand91** [comment]
Will look into it,
you may need to strip the x86_64 architecture from the WebRTC.framework. (First picture)

**Comment by DinuNuta** [comment]
"you may need to strip the x86_64 architecture from the WebRTC.framework"
How to do this?
Thanks.

**Comment by ethand91** [comment]
In the build process of your app add a Run Script task and have the script remove the unneeded architecture, something like this:
https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive

If you don't need the simulator architectures you could build the library yourself without the simulator architectures.

**Comment by ethand91** [comment]
Closing for now.
