### ISSUE TITLE
Support bitcode

### ISSUE THREAD

**Issue by ethand91** [ethand91/mediasoup-ios-client#4]
As the title says.

Rebuilding libwebrtc.a with bitcode support should resolve this.

**Comment by ethand91** [comment]
Supported bitcode for the mediasoup side, however the WebRTC side has still not been supported.
Enabling bitcode increases the size meaning it can't be pushed to github..

**Comment by mschonvogel** [comment]
Uploading the WebRTC binary to GitHub as a Release is not an option?

**Comment by ethand91** [comment]
@mschonvogel 
Enabling bitcode increased the size of the framework, using git lfs I could upload it but that's a pain...
I'll try and reduce the size a bit more (removing debug symbols etc.), failing that I will upload it as a zip file and have cocoapods download it prebuild.

**Comment by mschonvogel** [comment]
Awesome, thanks!!

Btw. cocoapods throws an error when trying to install the 1.1.0 / 1.1.1 release.

```
Pre-downloading: `mediasoup_ios_client` from `https://github.com/ethand91/mediasoup-ios-client.git`, submodules `true`, tag `1.1.1`

[!] Error installing mediasoup_ios_client
[!] Failed to download 'mediasoup_ios_client': [!] /usr/bin/git -C /var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200228-42675-1y6lx96 submodule update --init --recursive

Submodule path 'mediasoup-client-ios/dependencies/libmediasoupclient': checked out 'a75cf2a77ef1dd6b0b52b1a16596d65ef8fe6e83'
Submodule 'mediasoup-client-ios/dependencies/libmediasoupclient' (https://github.com/ethand91/libmediasoupclient.git) registered for path 'mediasoup-client-ios/dependencies/libmediasoupclient'
Submodule 'mediasoup-client-ios/dependencies/webrtc/src' (https://github.com/ethand91/webrtc-mac-src.git) registered for path 'mediasoup-client-ios/dependencies/webrtc/src'
Cloning into '/private/var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200228-42675-1y6lx96/mediasoup-client-ios/dependencies/libmediasoupclient'...
Cloning into '/private/var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200228-42675-1y6lx96/mediasoup-client-ios/dependencies/webrtc/src'...
error: Server does not allow request for unadvertised object fba755df2ea8163a5bbefb7e8e7c58dec433534a
Fetched in submodule path 'mediasoup-client-ios/dependencies/webrtc/src', but it did not contain fba755df2ea8163a5bbefb7e8e7c58dec433534a. Direct fetching of that commit failed.
```

**Comment by ethand91** [comment]
It's relating to the WebRTC Framework, I'll try and support it ASAP.
For now please use the older version of the library

**Comment by ethand91** [comment]
@mschonvogel Fixed! Please try re-downloading v1.1.1

**Comment by ethand91** [comment]
The size of the WebRTC framework with bitcode is 390Mb (without bitcode it is 12MB), even when compressed it exceeds Github's 100MB limit...
For that reason if you want bitcode support you will need to build the webrtc framework yourself.

**Comment by mschonvogel** [comment]
> @mschonvogel Fixed! Please try re-downloading v1.1.1

@ethand91 Thank you, but I'm getting the same error: 
```
Analyzing dependencies
Pre-downloading: `mediasoup_ios_client` from `https://github.com/ethand91/mediasoup-ios-client.git`, submodules `true`, tag `1.1.1`

[!] Error installing mediasoup_ios_client
[!] Failed to download 'mediasoup_ios_client': [!] /usr/bin/git -C /var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200302-92907-s823ru submodule update --init --recursive

Submodule path 'mediasoup-client-ios/dependencies/libmediasoupclient': checked out 'a75cf2a77ef1dd6b0b52b1a16596d65ef8fe6e83'
Submodule 'mediasoup-client-ios/dependencies/libmediasoupclient' (https://github.com/ethand91/libmediasoupclient.git) registered for path 'mediasoup-client-ios/dependencies/libmediasoupclient'
Submodule 'mediasoup-client-ios/dependencies/webrtc/src' (https://github.com/ethand91/webrtc-mac-src.git) registered for path 'mediasoup-client-ios/dependencies/webrtc/src'
Cloning into '/private/var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200302-92907-s823ru/mediasoup-client-ios/dependencies/libmediasoupclient'...
Cloning into '/private/var/folders/9d/7pfms1q53xzct6jx7wwjyh0c0000gn/T/d20200302-92907-s823ru/mediasoup-client-ios/dependencies/webrtc/src'...
error: Server does not allow request for unadvertised object fba755df2ea8163a5bbefb7e8e7c58dec433534a
Fetched in submodule path 'mediasoup-client-ios/dependencies/webrtc/src', but it did not contain fba755df2ea8163a5bbefb7e8e7c58dec433534a. Direct fetching of that commit failed.
```

In my Podfile:
```
pod 'mediasoup_ios_client', :git => 'https://github.com/ethand91/mediasoup-ios-client.git', :submodules => true, :tag => '1.1.1'
```


> The size of the WebRTC framework with bitcode is 390Mb (without bitcode it is 12MB), even when compressed it exceeds Github's 100MB limit...
> For that reason if you want bitcode support you will need to build the webrtc framework yourself.

Why don't you upload the compiled bitcode version of the WebRTC framework as a Release and then download it via cocoapods? GitHub releases allow you to upload files up to 2GB.

**Comment by ethand91** [comment]
Could you try changing the pod to:

`pod "mediasoup_ios_client"`

Then run the below and see if it works?
`pod deintegrate
pod install`

>Why don't you upload the compiled bitcode version of the WebRTC framework as a Release and then download it via cocoapods? GitHub releases allow you to upload files up to 2GB.

Thanks! Will try to do that.

**Comment by ethand91** [comment]
@mschonvogel  
The error you were getting was due to not updating the submodules..
Should be fixed now

**Comment by mschonvogel** [comment]
@ethand91 Thanks, it worked!
