### ISSUE TITLE
+[Mediasoupclient cleanup]: unrecognized selector sent to class 0x1022cb1e8

### ISSUE THREAD

**Issue by Rockjan** [ethand91/mediasoup-ios-client#40]
I can't understand that crash but there indeed has a declaration in the .h file.

I call this method when i prepared to dispose the sdk and finish a conference.
Maybe i called this method in a wrong way, please correct me,  thank you！

PS: I run the sdk with the version: 1.4.1 (upgrade from 1.2.3)

**Comment by Rockjan** [comment]
Also , about 10 seconds later after I dispose the sdk (without calling cleanup method), a crash occured:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType onConnectionStateChange:connectionState:]: unrecognized selector sent to instance 0x10e288400'
My code:
[self safeAsyncHandleWithBlock:^(MSMediaManager *weakSelf) {
        
        weakSelf.videoProducer._nativeTrack.isEnabled = NO;
        weakSelf.audioProducer._nativeTrack.isEnabled = NO;
        
        [weakSelf.videoProducer close];
        [weakSelf.audioProducer close];
        
        weakSelf.videoProducer = nil;
        weakSelf.audioProducer = nil;
        
        dispatch_async(dispatch_get_main_queue(), ^{
            [weakSelf.localVideoPresentView removeFromSuperview];
        });
        [weakSelf.consumerMap enumerateKeysAndObjectsUsingBlock:^(NSString * _Nonnull key, MSConsumerMedia * _Nonnull mediaData, BOOL * _Nonnull stop) {
            
            mediaData.audioConsumer._nativeTrack.isEnabled = NO;
            mediaData.videoConsumer._nativeTrack.isEnabled = NO;
            
            [mediaData.videoConsumer close];
            [mediaData.audioConsumer close];
            
            dispatch_async(dispatch_get_main_queue(), ^{
                [mediaData.videoPresentView removeFromSuperview];
            });
        }];
        
        [weakSelf.consumerMap removeAllObjects];
        
//        [Mediasoupclient cleanup];

        if (completion)
        {
            completion();
        }
        
    }];

and I created the transport as below:
  .
  .
  .
weakSelf.sendTransport = [weakSelf.device createSendTransport:weakSelf id:idStr iceParameters:iceParameters iceCandidates:iceCandidates dtlsParameters:dtlsParameters];
  .
  .
  .
Any suggestions?

**Comment by ethand91** [comment]
Regarding the second question did you close the transport?

**Comment by ethand91** [comment]
Regarding the first question, did you call Mediasoupclient initialize?
cleanup is not implemented in the android sdk so maybe it is not needed..

**Comment by Rockjan** [comment]
> Regarding the second question did you close the transport?

Er....It's my fault, I didn't call [transport close] method. Now it's OK.

I will be really appreciated if you can offer us a full Demo(include: init step -> normal usage step -> dispose step). I think there must be a lot of people like me that don't familiar with this Framework.

**Comment by Rockjan** [comment]
> Regarding the first question, did you call Mediasoupclient initialize?
> cleanup is not implemented in the android sdk so maybe it is not needed..

I have called [Mediasoupclient initializePC] before start a conference.

**Comment by ethand91** [comment]
There currently is a sample demo, although it's in Swift
https://github.com/ethand91/mediasoup-ios-client-sample

initializePC/cleanup methods don't seem to be needed so they will be removed in the next release.
Please don't call them in your application

**Comment by Rockjan** [comment]
OK， thanks。
