### ISSUE TITLE
Produce not disposed.

### ISSUE THREAD

**Issue by LucasDang** [ethand91/mediasoup-ios-client#41]
Hello, sorry to bother you again.

  I have met the problem that same problem as [https://mediasoup.discourse.group/t/failed-to-process-the-bundled-m-section/233](url). But my server has set pasue when created consumer, and I use latest framework.

  And I can reproduce this problem, I start video, close video, and restart video, and this problem happend. When I close producer, I found that it not disposed.

  So, I wanna to know that if you can reproduce it?

  Thanks!

**Comment by ethand91** [comment]
I couldn't reproduce this on my end.
Are you closing the relevant producer on the server side?

**Comment by LucasDang** [comment]
First I called method `close()` on producer, And then I send `closeproducer` request, 
but the ProducerListener delegate method `onTransportClose` has not been called. 

The server side code is same as Mediasoup official website demo.

Any idea? Thanks!

**Comment by LucasDang** [comment]
And I found if I not call `startCapture` on `videoCapturer`, that error would no happen.

Is this means when I close video and producer, actually, the connection is not closed?

**Comment by ethand91** [comment]
onTransportClose is called when the transport used by the producer is closed, this should not be called just by closing the producer.

I don't think startCapture is related to this issue. Could you try and reproduce it with my sample?

**Comment by LucasDang** [comment]
There's no problem with your demo.

Maybe I need learn more about webRTC. 

Thanks!
