### ISSUE TITLE
Reconnection after a network failure.

### ISSUE THREAD

**Issue by Rockjan** [ethand91/mediasoup-ios-client#42]
I can‘t find a way to reconnect after the app disconnected with server in your demo. Because mediasoup is more higher level than WebRTC.framework, we can't use WebRTC functions to handle the reconnection.  So what is the  best practice of a reconnection? Should we follow the steps as this: reinit a websocket and recreateTransport -> rejoinRoom -> recreateProducer -> recreateConsumer or mediasoup has another efficient way?

**Comment by ethand91** [comment]
If the socket is also disconnected you will have to follow the steps you provided.
If it's only the media you could try calling transport.restartIce

**Comment by Rockjan** [comment]
thx!
