### ISSUE TITLE
repeat implement

### ISSUE THREAD

**Issue by lihualin1688** [ethand91/mediasoup-ios-client#43]
objc[4784]: Class RTCEncodedImage is implemented in both /private/var/containers/Bundle/Application/C6374C37-10CF-4763-8FC7-7C808A2D924B/mediasoup-ios-cient-sample.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x105d96348) and /private/var/containers/Bundle/Application/C6374C37-10CF-4763-8FC7-7C808A2D924B/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x10559e760). One of the two will be used. Which one is undefined.
objc[4784]: Class RTCRtpFragmentationHeader is implemented in both /private/var/containers/Bundle/Application/C6374C37-10CF-4763-8FC7-7C808A2D924B/mediasoup-ios-cient-sample.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x105d96398) and /private/var/containers/Bundle/Application/C6374C37-10CF-4763-8FC7-7C808A2D924B/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x10559e7b0). One of the two will be used. Which one is undefined.

**Comment by ethand91** [comment]
https://github.com/ethand91/mediasoup-ios-client/issues/9
