### ISSUE TITLE
APP crashed on -[SendTransport produce:track:encodings:codecOptions] method. [ERROR] transport_wrapper::+[TransportWrapper nativeProduce:listener:track:encodings:codecOptions:appData:]() | The associated promise has been destructed prior to the associated state becoming ready.

### ISSUE THREAD

**Issue by pinguo-mazhong** [ethand91/mediasoup-ios-client#46]
Thank for writing this framework.
I met a crash when called -[SendTransport produce:track:encodings:codecOptions] method.
The error log shows as:[ERROR] transport_wrapper::+[TransportWrapper nativeProduce:listener:track:encodings:codecOptions:appData:]() | The associated promise has been destructed prior to the associated state becoming ready.
I'm using version 1.4.1
I pasted the total log in this file.
[errorLog.txt](https://github.com/ethand91/mediasoup-ios-client/files/4807641/errorLog.txt)

I also found out that  the NO.37 issue produced the same error, and I tried the method as MartinP7r said. But it does not work for me.
https://github.com/ethand91/mediasoup-ios-client/issues/37#issuecomment-641717357

if necessary, I can provide the source project.

Best Regards,
Michael

**Comment by LucasDang** [comment]
I met this error too, and I found if I called this method in a sync queue when produce audio and video, it's ok.  Maybe you can try.

**Comment by pinguo-mazhong** [comment]
> I met this error too, and I found if I called this method in a sync queue when produce audio and video, it's ok. Maybe you can try.
Thank for your suggestion.
I tried to put this code to main queue, but it still crash.
before:
![image](https://user-images.githubusercontent.com/11263816/85199485-8c295380-b322-11ea-8854-8ce3079077b5.png)
put this code to main queue:
![image](https://user-images.githubusercontent.com/11263816/85199531-dca0b100-b322-11ea-8f4f-808511f61def.png)

**Comment by LucasDang** [comment]
Ummm, just found that my error is not same as you. my error is about state of peerConnection, and carsh on this code too.

In your code, I have a doubt, why did you produce video after `websocket didConnect`?  
When did you create the transports?

**Comment by pinguo-mazhong** [comment]
> Ummm, just found that my error is not same as you. my error is about state of peerConnection, and carsh on this code too.
> 
> In your code, I have a doubt, why did you produce video after `websocket didConnect`?
> When did you create the transports?

我理解的是连接建立以后，再进行produce video操作。我看原作者的demo里也是这样的流程。
我这边是这样写的：
- (void)easySocketDidConnect {
    NSString *res = [LRMediaSoupRequest.sharedInstance sendGetRouterRtpCapabilitiesRequest:self.easySocket];
    NSString *routerRtpCapabilities = [LRCommonUtil pickValueFromJsonString:res forKey:@"data"];
    self.device = [Device new];
    [self.device load:routerRtpCapabilities];

    if (!self.device.isLoaded) {
        NSAssert(NO, @"device not loaded");
    }
    NSString *joinResponse = [LRMediaSoupRequest.sharedInstance sendJoinRequest:self.easySocket withDevice:self.device];
    // TODO: @mz joinResponse里可能有peer相关信息，查看是否有peer，并做相关处理
    [self createRecvTransport];
    [self createSendTransport];

    [self startVideo];
    [self startAudio];
}

> When did you create the transports?
我是在createRecvTransport和createSendTransport方法里创建transport的
![image](https://user-images.githubusercontent.com/11263816/85200524-ba129600-b32a-11ea-9eab-e8988d1d0b36.png)

**Comment by LucasDang** [comment]
你可能需要看一下 sendTransport 的代理方法 
```-(void)onProduce:(Transport *)transport kind:(NSString *)kind rtpParameters:(NSString *)rtpParameters appData:(NSString *)appData callback:(void(^)(NSString *))callback;```
这里你有没有callback一个字符串回去。

**Comment by pinguo-mazhong** [comment]
> 你可能需要看一下 sendTransport 的代理方法
> `-(void)onProduce:(Transport *)transport kind:(NSString *)kind rtpParameters:(NSString *)rtpParameters appData:(NSString *)appData callback:(void(^)(NSString *))callback;`
> 这里你有没有callback一个字符串回去。

太感谢你了，LucasDang。就是这里的问题，因为其他地方的问题，导致这里传给callback的值是空。终于解决了，感谢感谢！！！

**Comment by pinguo-mazhong** [comment]
已经解决了。
