### ISSUE TITLE
use VP8

### ISSUE THREAD

**Issue by lihualin1688** [ethand91/mediasoup-ios-client#47]
how can I use VP8, when i use VP8, did not work
-(instancetype)initWithNativeConsumer:(NSValue *)nativeConsumer {
    self = [super init];
    if (self) {
        self._nativeConsumer = nativeConsumer;
        
        webrtc::MediaStreamTrackInterface *nativeTrack = [ConsumerWrapper getNativeTrack:self._nativeConsumer];
        rtc::scoped_refptr<webrtc::MediaStreamTrackInterface> track(nativeTrack);

//        RTCPeerConnectionFactory *factory = [[RTCPeerConnectionFactory alloc] init];
  
        RTCVideoCodecInfo *info = [[RTCVideoCodecInfo alloc] initWithName:kRTCVideoCodecVp8Name];
        RTC_OBJC_TYPE(RTCDefaultVideoDecoderFactory) *decoderFactory = [[RTC_OBJC_TYPE(RTCDefaultVideoDecoderFactory) alloc] init];
        RTC_OBJC_TYPE(RTCDefaultVideoEncoderFactory) *encoderFactory = [[RTC_OBJC_TYPE(RTCDefaultVideoEncoderFactory) alloc] init];

        [encoderFactory setPreferredCodec:info];

        RTCPeerConnectionFactory *factory = [[RTC_OBJC_TYPE(RTCPeerConnectionFactory) alloc] initWithEncoderFactory:encoderFactory decoderFactory:decoderFactory];
        
        self._nativeTrack = [RTCMediaStreamTrack mediaTrackForNativeTrack:track factory:factory];
        free(factory);
    }
    
    return self;
}

**Comment by ethand91** [comment]
Make sure that VP8 is contained in the rtpCapabilities and rtpParameters.
You should not need to use RTCVideoCodecInfo

**Comment by lihualin1688** [comment]
I want use the webrtc SetFrameEncryptor api and injected frame,  but I don't know use, can you help me
