### ISSUE TITLE
The iOS Mediasoup library contains devices with the same name as the private API, causing the AppStore to be rejected

### ISSUE THREAD

**Issue by CJXB** [ethand91/mediasoup-ios-client#48]
The iOS Mediasoup library contains devices with the same name as the private API, causing the AppStore to be rejected

**Comment by CJXB** [comment]
Device.h

**Comment by ethand91** [comment]
Need a bit more info do we need to change Device.h to something else or just something in Device.h?

**Comment by CJXB** [comment]
Device.h，The class name needs to be changed

**Comment by ethand91** [comment]
Ok, will change it when I get time.
Can't be helped but I don't like the fact that the name will be different compared to the JS/Android clients :(

**Comment by xplatsolutions** [comment]
It sucks, but it's Apple and their very "uniqueness" in their App Store reviews, maybe we can at least make it contextual to the MediaStream API used in JavaScript.

**MediaStream (GetUserMedia)**
`The MediaStream API provides a way to access device cameras and microphones using JavaScript. It controls where multimedia stream data is consumed, and provides some control over the devices that produce the media. It also exposes information about devices able to capture and render media.`

Suggested name: `MediaStreamDevice`

**Comment by ethand91** [comment]
I would agree however in this case the Device only calls mediasoup methods.
I'll rename it to MediasoupDevice

**Comment by xplatsolutions** [comment]
Funny it was the first naming convention came to my mind and it makes more sense.

**Comment by ethand91** [comment]
Fixed in 1.5.0
