### ISSUE TITLE
Does not support vp9

### ISSUE THREAD

**Issue by a42279395** [ethand91/mediasoup-ios-client#5]
Hello, not in the demo webRTC does not support vp9, I changed a new webTRC, cause crashes.

**Comment by ethand91** [comment]
Hello,
unlike android VP9 is not enabled by default, I will try and enable VP9 support along with bitcode.

**Comment by ethand91** [comment]
Implemented, however this size of the WebRTC.framework doesn't allow me to push it..
I'll try to reduce the size of the framework, but if you need it soon I could also provide the framework via download.

**Comment by a42279395** [comment]
Thank you very much, I need to download the latest demo?Where should I download.

**Comment by a42279395** [comment]
You also need to trouble you, I want to learn how to generate libraries, can you teach me?

**Comment by a42279395** [comment]
![5C135B84-26E6-4CD9-B0CB-4DD76B4AE4B2](https://user-images.githubusercontent.com/30998528/75602305-e053c200-5afe-11ea-94d8-0160faa19fc7.png)

Hello how to solve this problem?Thank you very much, your guidance

**Comment by a42279395** [comment]
Hello, could you please provide a support vp9 can download?Appeared when I compile errors.Didn't get it, thank you for your know.

**Comment by a42279395** [comment]
![A5318E8C-B60D-42D7-AB6A-EBCA3F81698C](https://user-images.githubusercontent.com/30998528/75620561-2a06e000-5bc5-11ea-9e33-b7df7133551c.png)
This is my compile-time errors, don't know how to solve.Bother you guidance, thank you very much

**Comment by ethand91** [comment]
Did you download the submodules?

**Comment by a42279395** [comment]
I didn't see what you mean, I am in accordance with the iOS WebRTC Framework Build Instructions to compile, you can give me a detailed steps?thank you！

**Comment by a42279395** [comment]
webRTC已经编译好了。

**Comment by a42279395** [comment]
Where is the submodules download?

**Comment by ethand91** [comment]
Hello, I have included VP9 support in version 1.1.1 of the library.
You shouldn't need to build it yourself unless you need bitcode support.
