### ISSUE TITLE
Hello, the App Store shelf audit suggested that the logger. h in our library also has the same name as the system's private API and needs to be changed

### ISSUE THREAD

**Issue by CJXB** [ethand91/mediasoup-ios-client#51]
Hello, the App Store shelf audit suggested that the logger. h in our library also has the same name as the system's private API and needs to be changed

**Comment by CJXB** [comment]
And these, too  ：animatorDidAnimate :, animatorWillAnimate :, localDescription，pop_animation：didReachProgress :, pop_animationDidApply :, pop_animationDidReachToValue :, pop_animationDidsideded ::，pop_animationDids :: ：，setPreferredCodec :, videoSource

**Comment by CJXB** [comment]
ITMS-90338: Non-public API usage - The app references non-public selectors in *****: animatorDidAnimate:, animatorWillAnimate:, localDescription, pop_animation:didReachProgress:, pop_animationDidApply:, pop_animationDidReachToValue:, pop_animationDidStart:, pop_animationDidStop:finished:, sdp, setIsEnabled:, setPreferredCodec:, videoSource. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by LucasDang** [comment]
The localDescription is belong WebRTC, maybe you can google to find a solution.

**Comment by ethand91** [comment]
This is a libwebrtc issue
