### ISSUE TITLE
Hello, may I ask if there is any other way to pack our library? Our pods were not successful

### ISSUE THREAD

**Issue by CJXB** [ethand91/mediasoup-ios-client#52]
Hello, may I ask if there is any other way to pack our library? Our pods were not successful

**Comment by ethand91** [comment]
Why was the pod not successful?
You could try and build the library yourself and include it as a static framework

**Comment by CJXB** [comment]
Could you please tell me how to package yourself "Mediasoup_ios_client.framwork"? Can you provide the packaging method? "Webrtc. framwork" needs to be separately extracted and cannot be included in "Mediasoup_ios_client.framwork"

**Comment by ethand91** [comment]
If your not using the pod, mediasoup_ios_client.framework and WebRTC.framework must be referenced separately.

**Comment by CJXB** [comment]
Can I directly refer to the WebrtC. framework in "Mediasoup_ios_client.framwork"

**Comment by CJXB** [comment]
> If your not using the pod, mediasoup_ios_client.framework and WebRTC.framework must be referenced separately.
Can I directly refer to the WebrtC. framework in "Mediasoup_ios_client.framwork"
Again, I have to recompile "mediasoup_ios_client.framwork" to get "webrtc. framwork" out of it

**Comment by ethand91** [comment]
Yes try putting both of them in your FRAMEWORK_SEARCH_PATH

**Comment by CJXB** [comment]
> 是的，请尝试将它们都放入您的FRAMEWORK_SEARCH_PATH

Ok, thank you
