### ISSUE TITLE
Is support broadcasters and svc

### ISSUE THREAD

**Issue by lihualin1688** [ethand91/mediasoup-ios-client#56]
Does the library support broadcasters and SVC? If supported, how do I configure it?

**Comment by ethand91** [comment]
The library supports it, however due to a bug it can't be used ATM.
Will try and fix it.

**Comment by ethand91** [comment]
Not sure what you mean by "broadcasters", however to enable VP9 SVC you would need to configure the inner libmediasoupclient 
https://mediasoup.org/documentation/v3/mediasoup/rtp-parameters-and-capabilities/#SVC
