### ISSUE TITLE
 Where can I find the file “Device.h”

### ISSUE THREAD

**Issue by Ayukey** [ethand91/mediasoup-ios-client#58]
error: mediasoup-ios-client/mediasoup-client-ios/include/Device.h: No such file or directory (in target 'mediasoup-client-ios' from project 'mediasoup-client-ios')

**Comment by xplatsolutions** [comment]
The file has changed in latest version, it is now MediasoupDevice.h due to Apple rejecting the app with naming conflict in their private APIs.

**Comment by ethand91** [comment]
@xplatsolutions  Thanks

**Comment by Ayukey** [comment]
@xplatsolutions Thanks
