### ISSUE TITLE
Hope to receive your guidance

### ISSUE THREAD

**Issue by a42279395** [ethand91/mediasoup-ios-client#8]
![AA79A8E1-9020-4A1F-83D5-3FFEF822683C](https://user-images.githubusercontent.com/30998528/75656813-c2719300-5c9f-11ea-8a80-5aa54170d9de.png)
Hello, I use mediasoup directly - ios - the client - master/build/mediasoup_client_ios framework test, and doesn't support vp9.Or am I using method is not correct.Request you to give me a clear instruction.Very thank you.

**Comment by ethand91** [comment]
Could you try it using cocoapods?

**Comment by a42279395** [comment]
![2C9DED38-9D21-4770-BA7A-FD73576FFABF](https://user-images.githubusercontent.com/30998528/75745788-4f295900-5d53-11ea-9288-1fad3b34713e.png)
Hello, I'm very sorry, I use cocoapods an error has occurred.Is my operation problems?Sorry to trouble you!Thank you for your guidance.

**Comment by ethand91** [comment]
Hello,
Sorry it was an issue on my end, could you please try re-installing?

**Comment by a42279395** [comment]
![2C4F7676-0DAD-4176-BE0F-28D45C1A52D8](https://user-images.githubusercontent.com/30998528/75748402-5869f400-5d5a-11ea-8fd8-7832434a66fb.png)
Hello, I have tried to reinstall, but still have a problem?Thank you for your guidance!

**Comment by ethand91** [comment]
You can update using the following commands:
```
pod repo update
pod deintegrate
pod install
```
