### ISSUE TITLE
AudioEncoder Thread Error

### ISSUE THREAD

**Issue by 435129214** [ethand91/mediasoup-ios-client#82]
Recently, accidental crashes often occur. I just converted the project into a Mac project in strict accordance with the code used in demo. The specific error is as follows. I don't have an idea whether it happened or if there is any good way to locate it.
<img width="1190" alt="截屏2020-09-12 上午10 11 49" src="https://user-images.githubusercontent.com/16433951/92984959-f811f700-f4e0-11ea-8027-2b2133915e73.png">

**Comment by 435129214** [comment]
1、
(probe_bitrate_estimator.cc:159): Probing successful [cluster id: 6] [send: 4672 bytes / 39 ms = 958358 bps ] [receive: 4672 bytes / 35 ms = 1067885 bps]
(probe_controller.cc:280): Measured bitrate: 500000 Minimum to probe further: 700000
(bitrate_allocator.cc:394): Current BWE 500000
(probe_controller.cc:378): kWaitingForProbingResult: timeout

2、
(bitrate_allocator.cc:523): UpdateAllocationLimits : total_requested_min_bitrate: 94 kbps, total_requested_padding_bitrate: 0 bps, total_requested_max_bitrate: 2564 kbps
(bitrate_prober.cc:112): Probe cluster (bitrate:min bytes:min packets): (2564000:4808:5)
(bitrate_prober.cc:112): Probe cluster (bitrate:min bytes:min packets): (5000000:9375:5)
(rtp_sender_video.cc:623): Sent first RTP packet of the first video frame (pre-pacer)
YRTCDemo(49037,0x700001734000) malloc: Heap corruption detected, free list is damaged at 0x600003503d30
*** Incorrect guard value: 0
(49037,0x700001734000) malloc: *** set a breakpoint in malloc_error_break to debug

3、
(video_stream_encoder.cc:1329): Encoder settings changed from EncoderInfo { ScalingSettings { min_pixels_per_frame = 57600 }, requested_resolution_alignment = 1, supports_native_handle = 0, implementation_name = 'unknown', has_trusted_rate_controller = 0, is_hardware_accelerated = 1, has_internal_source = 0, fps_allocation = [[ 1] ], resolution_bitrate_limits = [] , supports_simulcast = 0} to EncoderInfo { ScalingSettings { Thresholds { low = 29, high = 95}, min_pixels_per_frame = 57600 }, requested_resolution_alignment = 1, supports_native_handle = 0, implementation_name = 'libvpx', has_trusted_rate_controller = 0, is_hardware_accelerated = 0, has_internal_source = 0, fps_allocation = [[ 1] ], resolution_bitrate_limits = [] , supports_simulcast = 1}
(rtp_sender_video.cc:623): Sent first RTP packet of the first video frame (pre-pacer)
YRTCDemo(49376,0x70000ba81000) malloc: Heap corruption detected, free list is damaged at 0x600003524b00
*** Incorrect guard value: 0
(49376,0x70000ba81000) malloc: *** set a breakpoint in malloc_error_break to debug

4、
(trendline_estimator.cc:185): Using Trendline filter for delay change estimation with settings sort:false,cap:false,beginning_packets:7,end_packets:7,cap_uncertainty:0,window_size:20 and no network state predictor
(trendline_estimator.cc:185): Using Trendline filter for delay change estimation with settings sort:false,cap:false,beginning_packets:7,end_packets:7,cap_uncertainty:0,window_size:20 and no network state predictor
YRTCDemo(50705,0x700005333000) malloc: Heap corruption detected, free list is damaged at 0x6000035156b0
*** Incorrect guard value: 0
(50705,0x700005333000) malloc: *** set a breakpoint in malloc_error_break to debug

5、
(bitrate_prober.cc:112): Probe cluster (bitrate:min bytes:min packets): (2564000:4808:5)
(bitrate_prober.cc:112): Probe cluster (bitrate:min bytes:min packets): (5000000:9375:5)
(rtp_sender_video.cc:623): Sent first RTP packet of the first video frame (pre-pacer)
YRTCDemo(51432,0x700010c4b000) malloc: Heap corruption detected, free list is damaged at 0x600003508dc0
*** Incorrect guard value: 0
(51432,0x700010c4b000) malloc: *** set a breakpoint in malloc_error_break to debug
(lldb)  

6、(agc_manager_direct.cc:351): [agc] rms_error=28, target_compression=10, residual_gain=15
(rtcp_receiver.cc:315): absl::optional<TimeDelta> webrtc::RTCPReceiver::OnPeriodicRttUpdate(webrtc::Timestamp, bool): Timeout: No increase in RTCP RR extended highest sequence number.


#
# Fatal error in: ../../modules/audio_device/audio_device_buffer.cc, line 460
# last system error: 0
# Check failed: time_to_wait_ms > 0 (-43530 vs. 0)
# Invalid timer interval(thread.cc:684): Message took 2626ms to dispatch. Posted from: PostDelayedTask@../../rtc_base/thread.cc:1034

This is some of the other questions I've recorded, and it feels like a problem

**Comment by ethand91** [comment]
Haven't tried to use this project on a mac, I only made it for iOS.
Sorry I can't help.
