### ISSUE TITLE
APP STORE ISSUES

### ISSUE THREAD

**Issue by sivakumaraketi** [ethand91/mediasoup-ios-client#85]
I am getting below mediasoup related issue when uploading the appstore

App Store Connect Operation Error
ERROR ITMS-90087: “Unsupported Architectures. The executable for encounternow.app/Frameworks/mediasoup_client_ios.framework/Frameworks/WebRTC.framework contains unsupported architectures ‘[i386, x86_64]’.”
App Store Connect Operation Error
ERROR ITMS-90685: “CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value ‘org.webrtc.WebRTC’ under the iOS application ‘encounternow.app’.”
App Store Connect Operation Error
ERROR ITMS-90209: “Invalid Segment Alignment. The app binary at ‘encounternow.app/Frameworks/mediasoup_client_ios.framework/Frameworks/WebRTC.framework/WebRTC’ does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.”
App Store Connect Operation Error
ERROR ITMS-90205: “Invalid Bundle. The bundle at ‘encounternow.app/Frameworks/mediasoup_client_ios.framework’ contains disallowed nested bundles.”
App Store Connect Operation Error
ERROR ITMS-90206: “Invalid Bundle. The bundle at ‘encounternow.app/Frameworks/mediasoup_client_ios.framework’ contains disallowed file ‘Frameworks’.”
App Store Connect Operation Error
ERROR ITMS-90125: “The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple’s linker.”
App Store Connect Operation Warning
WARNING ITMS-90806: “CFBundleIdentifier collision. Each bundle must have a unique bundle identifier. The bundle identifier ‘org.webrtc.WebRTC’ is used in the bundles ‘[Payload/encounternow.app/Frameworks/mediasoup_client_ios.framework/Frameworks/WebRTC.framework, Payload/encounternow.app/Frameworks/WebRTC.framework]’”
App Store Connect Operation Warning
WARNING ITMS-90080: “The executable ‘Payload/encounternow.app/Frameworks/mediasoup_client_ios.framework/Frameworks/WebRTC.framework’ is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library.”

**Comment by sivakumaraketi** [comment]
using pod https://cocoapods.org/pods/mediasoup_ios_client

**Comment by tanaymondal** [comment]
App Store doesn't support simulator architecture [i386, x86_64]. Use the below command to strip unsupported architecture.
lipo -remove i386 Framework_SDK -o Framework_SDK 
lipo -remove x86_64 Framework_SDK -o Framework_SDK

**Comment by tanaymondal** [comment]
Are you using media soup demo server or mediasoup-sample-server by ethand91? I am working with mediaSoup demo server to make the mediaSoup iOS demo app, but facing multiple issues.
1. I am unable to produce video but audio.
2. I am not getting newConsumer socket request, because of that, I am not able to consume video/audio.

Can you help me with these?
Is your project open source?
