### ISSUE TITLE
Failed to set local answer sdp: Failed to process the bundled m= section.

### ISSUE THREAD

**Issue by LucasDang** [ethand91/mediasoup-ios-client#87]
またお邪魔して申し訳ありません

Encountered a very strange problem,

When I receive consumers and handle them in a serial Dispatch Queue, 
the following sequence will crash with message `Failed to set local answer sdp: Failed to process the bundled m= section`.
1.peerA.audio——peerA.video——peerB.audio
2.peerA.audio——peerA.video——peerB.audio——peerB.video

But following sequence is OK.
3.peerA.audio——peerB.audio
4.peerA.audio——peerA.video——peerB.video——peerB.audio

Can you tell me where the problem is?

Thanks anyway!

**Comment by LucasDang** [comment]
Found the reason, I send response to server is too early.

**Comment by qaz1991815** [comment]
I also met the same problem. How did you solve it?

**Comment by LucasDang** [comment]
> I also met the same problem. How did you solve it?

When you receive `newConsumer` request, you need create local consumer first, and then send response to server.

**Comment by qaz1991815** [comment]
目前流程就是按照这个逻辑的，1对1通话没问题，但是如果3人或者以上还是会有这个问题。

**Comment by LucasDang** [comment]
> 目前流程就是按照这个逻辑的，1对1通话没问题，但是如果3人或者以上还是会有这个问题。

你确定你是在一个队列中同步操作的么？你得创建完成`consumer`之后在发送`response`给服务端。

**Comment by qaz1991815** [comment]
没有使用队列，不过从打印信息来看，是创建完成后，通过resumeConsumer恢复音视频的。你能分享你的代码片段吗，这个问题困扰我好久了，非常感谢！
<img width="790" alt="截屏2021-02-22 下午6 26 09" src="https://user-images.githubusercontent.com/31402452/108696005-efb3f280-753b-11eb-8d1b-0eb5cc36656b.png">
<img width="1075" alt="截屏2021-02-22 下午6 34 40" src="https://user-images.githubusercontent.com/31402452/108696570-b039d600-753c-11eb-9998-7b1ca8f969b0.png">
<img width="613" alt="截屏2021-02-22 下午6 34 58" src="https://user-images.githubusercontent.com/31402452/108696585-b6c84d80-753c-11eb-9945-e9fd3d7b8199.png">

**Comment by LucasDang** [comment]
> 没有使用队列，不过从打印信息来看，是创建完成后，通过resumeConsumer恢复音视频的。你能分享你的代码片段吗，这个问题困扰我好久了，非常感谢！
> <img alt="截屏2021-02-22 下午6 26 09" width="790" src="https://user-images.githubusercontent.com/31402452/108696005-efb3f280-753b-11eb-8d1b-0eb5cc36656b.png">
> <img alt="截屏2021-02-22 下午6 34 40" width="1075" src="https://user-images.githubusercontent.com/31402452/108696570-b039d600-753c-11eb-9998-7b1ca8f969b0.png">
> <img alt="截屏2021-02-22 下午6 34 58" width="613" src="https://user-images.githubusercontent.com/31402452/108696585-b6c84d80-753c-11eb-9945-e9fd3d7b8199.png">

不是手动的`resumeConsumer`，你在接收到`websocket`的`request`，是否返回了`response`？
![074E4C15-F1C7-49FA-966F-106E39993EB3](https://user-images.githubusercontent.com/14243627/108698550-36571c00-753f-11eb-9c17-c3c575819bb6.png)
我这里接收到`newConsumer`，通过`transport`创建完成之后，使用闭包回调去发送`response`的信令

**Comment by qaz1991815** [comment]
没有返回response，这个response信令内容是啥？有格式要求吗？

**Comment by LucasDang** [comment]
> 没有返回response，这个response信令内容是啥？有格式要求吗？

每个人 写法 不一样，我这里是通过回给服务端`response`，服务端对此`consumer`进行`resume` 。
这个你可能需要和你服务端联调一下。
`https://mediasoup.discourse.group/t/create-server-side-consumers-with-paused-true/244`
要做的就是接收到第二个`audioConsumer`的时候必须要在本地创建完成相应的`consumer`之后，才能开启音频数据的传输。

**Comment by qaz1991815** [comment]
好的，非常感谢
