### ISSUE TITLE
RevTransport.close() EXC_BAD_ACCESS Crash

### ISSUE THREAD

**Issue by it-hoon** [ethand91/mediasoup-ios-client#88]
Error when invoking RevTransport.close().

Thread 1: EXC_BAD_ACCESS (code=1, address=0x22b28b9e0)

What are the solutions?

**Comment by it-hoon** [comment]
+[TransportWrapper nativeFreeTransport:]: unrecognized selector sent to class 0x1068d3160"

**Comment by ethand91** [comment]
Are you sure you are not already closing it?

**Comment by ethand91** [comment]
That or this is a copy of
https://github.com/ethand91/mediasoup-ios-client/issues/92
