### ISSUE TITLE
AURemoteIO.cpp:1086:Initialize: failed: -66635 (enable 3, outf< 1 ch,  48000 Hz, Int16> inf< 1 ch,  48000 Hz, Int16>)

### ISSUE THREAD

**Issue by qaz1991815** [ethand91/mediasoup-ios-client#95]
Hello, I'm testing two IOS devices and found some problems. It is an error found when creating audio producer. It will cause the remote screen to be black (occasionally). This is not the case when I annotate startaudio().

**Comment by cavoixanh** [comment]
I finished sample. I can tell, I also receive it, but still can video call.

**Comment by ethand91** [comment]
Please share the logs, also:
1. Does this happen on both the devices?
2. Whats the device and the OS version?

**Comment by qaz1991815** [comment]
I think I've solved it. Just use self.startVideo Used before () self.startAudio (), but I don't know why. Thank you for your reply
